cache:
  defaultExpirationInSeconds: 60

kafka:
  bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
  producer:
    delivery-timeout-ms: 10000
    enable-idempotence: true
    max-block-ms: 10000
    retries: 3
    retry-backoff-ms: 1000
    request-timeout-ms: 5000
  consumer:
    session-timeout-ms: 10000
    use-type-info-header: false
    max-partition-fetch-bytes: 300000
    max-poll-interval-ms: 300000
    max-poll-records: 10
    enable-auto-commit: false
    auto-offset-commit: earliest
    heartbeat-interval-ms: 3000
    group-id:
      transaction: t1-demo-transaction-group
      transaction-accept: t1-demo-transaction-accept-group
      metric: t1-demo-metric-group
      transaction-result: t1-demo-transaction-result-group
  topic:
    metrics: t1_demo_metrics
    transaction: t1_demo_transaction
    transaction-accept: t1_demo_transaction_accept
    transaction-result: t1_demo_transaction_result

logging:
  level:
    org.springframework: INFO

metric:
  maximumMethodDurationInMillis: 1000

service-2:
  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ5MzcyNjgyLCJleHAiOjE3NTE5NjQ2ODJ9.zoutEisz1wH2xCLZVRhLaHmnpryNpqlQ_aGA3_slsIK1ffPayz9qsHkytECFazzwEgB9rpQAlQl-cmJ17fVLxw
  url: http://service-2:8080

spring:
  application:
    name: t1-mainProject
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

transactions:
  maxNumberOfRejectedTransactionsByClient: 2